version: '3'

services:

  www:
    image: 'tmvdl/projects:app'
    build: './src/app'
    volumes:
      - './src/app/html:/usr/share/nginx/html'
    ports:
      -  '80:80'

  github-release:
    image: 'github-release'
    build: './src'
