version: '3'

services:

  nodejs:
    image: 'tmvdl/projects:nodejs'
    build: 
      context: './src/app'
      dockerfile: Dockerfile.nodejs
    volumes:
      - './src/app/html:/usr/share/nginx/html'

  app:
    image: 'tmvdl/projects:app'
    build: './src/app'
    volumes:
      - './src/app/html:/usr/share/nginx/html'
    ports:
      -  '8080:80'

  github-release:
    image: 'github-release'
    build: './src'
